name: Daily Sales Scraper

on:
  schedule:
    - cron: "0 6 * * *"   # Runs daily at 3:00 UTC
  workflow_dispatch:       # Allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r Scrapper/requirements.txt
          playwright install chromium
          playwright install-deps

      - name: Run Scraper
        env:
          host: ${{ secrets.host }}
          database: ${{ secrets.database }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          port: ${{ secrets.port }}
          SALESFLO_USERNAME: ${{ secrets.SALESFLO_USERNAME }}
          SALESFLO_PASSWORD: ${{ secrets.SALESFLO_PASSWORD }}
          SALESFLO_USERNAME2: ${{ secrets.SALESFLO_USERNAME2 }}
          SALESFLO_PASSWORD2: ${{ secrets.SALESFLO_PASSWORD2 }}
        run: |
         python Scrapper/bott.py
